export let englishContent = [
	"Introduce",
	"Works",
	"Testimonials",
	"Services",
	"Contact",
	"Blog",
	"Elevate Your Digital Presence with me",
	"Welcome to my digital world, where innovation and functionality converge to create exceptional web experiences. As a seasoned full stack web developer, I specialize in transforming your ideas into seamless, user-friendly websites.",
	"WORK WITH ME !",
	"Frontend",
	"I specialize in creating captivating user interfaces through expert use of HTML, CSS, JavaScript, Bootstrap and Sass delivering seamless and engaging website experiences.",
	"Backend",
	"With expertise in server-side scripting and database management, I architect with PHP and MySQL, robust backend systems that power websites with efficiency and reliability.",
	"WordPress",
	"I leverage the flexibility of WordPress to craft dynamic websites with custom themes and plugins, marrying design with functionality for a seamless user experience.",
	"SEO",
	"My SEO proficiency ensures your website not only looks great but also ranks well, driving targeted organic traffic through strategic optimization techniques.",
	"Introduce",
	"Hello! I'm Abdelkarim Achlaih",
	"Every great development begins with a clear vision, meticulous planning, and a commitment to turning ideas into elegant, functional solutions.",
	"Your ally in the realm of web development. In a world saturated with cookie-cutter websites, I bring a breath of fresh air. My two years of experience as a full stack web developer empower me to craft tailored solutions that speak to your unique project requirements.",
	"Latest Works",
	"Perfect solutions for digital experience",
	"Fylo Website",
	"Live Demo",
	"View Code",
	"Blog Website",
	"Live Demo",
	"View Code",
	"Github Repos App",
	"Live Demo",
	"View Code",
	"Currency Converter",
	"Live Demo",
	"View Code",
	"Gaming Template",
	"Live Demo",
	"View Code",
	"All projects",
	"* Browse other projects on my github",
	"",
	"",
	"",
];
export let frenchContent = [
	"Introduire",
	"Travaux",
	"Témoignages",
	"Services",
	"Contact",
	"Blog",
	"Améliorez votre présence numérique avec moi",
	"Bienvenue dans mon monde numérique, où l'innovation et la fonctionnalité convergent pour créer des expériences web exceptionnelles. En tant que développeur web expérimenté, je me spécialise dans la transformation de vos idées en sites web transparents et conviviaux.",
	"TRAVAILLEZ AVEC MOI !",
	"Frontend",
	"Je suis spécialisée dans la création d'interfaces utilisateur captivantes grâce à l'utilisation experte de HTML, CSS, JavaScript, Bootstrap et Sass, ce qui permet de créer des sites Web transparents et attrayants.",
	"Backend",
	"Grâce à mon expertise dans le domaine des scripts côté serveur et de la gestion des bases de données, je conçois, avec PHP et MySQL, des systèmes dorsaux robustes qui alimentent les sites web avec efficacité et fiabilité.",
	"WordPress",
	"J'exploite la flexibilité de WordPress pour créer des sites web dynamiques avec des thèmes et des plugins personnalisés, en mariant le design et la fonctionnalité pour une expérience utilisateur transparente.",
	"Référencement Web",
	"Mes compétences en matière de référencement garantissent que votre site Web ne se contente pas d'avoir une belle apparence, mais qu'il se classe également bien, en générant un trafic organique ciblé grâce à des techniques d'optimisation stratégiques.",
	"Introduire",
	"Bonjour ! Je suis Abdelkarim Achlaih",
	"Tout grand projet de développement commence par une vision claire, une planification méticuleuse et un engagement à transformer les idées en solutions élégantes et fonctionnelles.",
	"Votre allié dans le domaine du développement web. Dans un monde saturé de sites web à l'emportepièce, j'apporte une bouffée d'air frais. Mes deux années d'expérience en tant que développeur web full stack me permettent de concevoir des solutions sur mesure qui répondent aux exigences uniques de votre projet.",

	"Derniers travaux",
	"Des solutions parfaites pour l'expérience numérique",

	"Site web Fylo",
	"Démonstration en direct",
	"Voir le code",

	"Site web de blog",
	"Démonstration en direct",
	"Voir le code",

	"Application GitHub",
	"Démonstration en direct",
	"Voir le code",

	"Converteur de devises",
	"Démonstration en direct",
	"Voir le code",

	"Gaming template",
	"Démonstration en direct",
	"Voir le code",

	"Tous les projets",
	"* Parcourir d'autres projets sur mon github",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
];
