export let projects = [
	{
		name: "Roibeasts Real Estate",
		techs: ["WordPress"],
		imgLink: "Landings.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Currency_App/",
		codeLink: ".",
		desc: "In these projects, I transformed given PSD designs into fully functional websites using HTML, CSS, and JavaScript. Some of them have an integrated API that fetches data in real time, in order to prevent page multiple reloadings. I meticulously coded and optimized the design to ensure it's responsive and accessible, providing a seamless user experience across various devices and browsers.",
		types: ["Projects", "Blogs"],
	},
	{
		name: "Kiosque CAFC Marketplace",
		techs: ["WordPress"],
		imgLink: "Landings.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Currency_App/",
		codeLink: "",
		desc: "In these projects, I transformed given PSD designs into fully functional websites using HTML, CSS, and JavaScript. Some of them have an integrated API that fetches data in real time, in order to prevent page multiple reloadings. I meticulously coded and optimized the design to ensure it's responsive and accessible, providing a seamless user experience across various devices and browsers.",
		types: ["Projects", "Stores"],
	},
	{
		name: "Landing Pages",
		techs: ["Bootstrap", "JavaScript", "Sass"],
		imgLink: "Landings.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Currency_App/",
		codeLink: "",
		desc: "In these projects, I transformed given PSD designs into fully functional websites using HTML, CSS, and JavaScript. Some of them have an integrated API that fetches data in real time, in order to prevent page multiple reloadings. I meticulously coded and optimized the design to ensure it's responsive and accessible, providing a seamless user experience across various devices and browsers.",
		types: ["Templates"],
	},
	{
		name: "Modern UI Designs",
		techs: ["HTML", "CSS"],
		imgLink: "Modern UI Designs.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Fylo/",
		codeLink: "",
		desc: "In this project, I transformed given PSD designs into fully functional websites using HTML and CSS. I meticulously coded and optimized the designs to ensure their responsiveness, providing a seamless user experience across various devices and browsers.",
		types: ["Templates"],
	},
	{
		name: "Scroll Activated Animations",
		techs: ["Bootstrap", "JavaScript", "Sass"],
		imgLink: "Next-Gen.png",
		demoLink:
			"https://abdelkarim-achlaih.github.io/Next-Gen-Solutions-Website/",
		codeLink: "",
		desc: "If you asked me, what is your top 5 projects, I'm pretty sure that this one has a place among them, in this project, I tried to make the layout more interactive with the user inputs, such as on mouse move or on scrolling, so you will find a lot of animations, loaders, pinned sections, scroll activated animations... all these features have implemented with HTML, CSS, JavaScript, Bootstrap, Sass, GSAP, Particles.Js, Lenis.Js... and of course a lot of time and dedicated hard work.",
		types: ["Templates"],
	},
	{
		name: "Blog Website",
		techs: ["WordPress", "JavaScript", "Sass", "Bootstrap"],
		imgLink: "Nexus Blog.png",
		demoLink: "http://myblog.abdelkarim.rf.gd/",
		codeLink: "",
		desc: "Developing a customized WordPress theme for a personal blog website using HTML, CSS, JavaScript, Sass, Bootstrap, PHP, and WordPress. This project started by installing a new customized theme, based on the PHP Loop provided by WordPress, pages, posts, and sidebars, then editing their appearance and responsiveness across all devices using Bootstrap and Sass, and some JavaScript to fix issues cannot be handled using just HTML and CSS.",
		types: ["Demos", "Blogs"],
	},
	{
		name: "Startup Website",
		techs: ["WordPress", "JavaScript", "Sass", "Bootstrap"],
		imgLink: "Stara Immo.png",
		demoLink: "https://staraimmo.ma",
		codeLink: "",
		desc: "This project highlights the services provided by a building construction company, the website was built under the requirements provided by the in-house marketing strategist. the website is SEO Friendly, not built by Elementor or another plugin, but the owner wanted to have a customized theme that suits his domain of expertise. So I built a new theme from scratch using mainly Bootstrap and Sass, configuring the backend using WordPress PHP Loops, sidebars, pages, and installing plugins such as WPforms.",
		types: ["Projects"],
	},
	{
		name: "Online Store",
		techs: ["WordPress"],
		imgLink: "SuitedUp.png",
		demoLink: "http://suitedup.rf.gd/",
		codeLink: "",
		desc: "In this project, I initiated the development process with a thorough WooCommerce store setup, configuring product categories, attributes, and payment gateways with Stripe to create a fully functional e-commerce platform. My focus was on designing a user-friendly and visually appealing online store, optimizing product listings, implementing secure transaction processing, and integrating essential e-commerce features for a seamless shopping experience.",
		types: ["Demos", "Stores"],
	},
	{
		name: "Online Community",
		techs: ["PHP", "MySQL", "JavaScript", "CSS"],
		imgLink: "PHP App.png",
		demoLink: "http://blog.abdelkarim.rf.gd/",
		codeLink: "",
		desc: "In this project, I began with the design of a robust MySQL database, establishing a structured foundation for a feature-rich PHP and MySQL-based blog system. This system offer user registration, content management, categorization, and interaction features using HTML, CSS and JavaScript, with a strong focus on security and responsive web design.",
		types: ["Projects", "Demos", "Blogs"],
	},
	{
		name: "PSD Conversion",
		techs: ["HTML", "CSS"],
		imgLink: "Template 1.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Template-One/",
		codeLink: "",
		desc: "In this project, I transformed a given PSD design into a fully functional website using HTML and CSS. I meticulously coded and optimized the design to ensure it's responsive and accessible, providing a seamless user experience across various devices and browsers.",
		types: ["templates"],
	},
	{
		name: "PSD Conversion",
		techs: ["HTML", "CSS", "JavaScript"],
		imgLink: "Template 2.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Template-Two/",
		codeLink: "",
		desc: "In this project, I transformed a given PSD design into a fully functional website using HTML, CSS and JavaScript. I meticulously coded and optimized the design to ensure it's responsive and accessible, providing a seamless user experience across various devices and browsers.",
		types: ["templates"],
	},
	{
		name: "PSD Conversion",
		techs: ["HTML", "CSS", "JavaScript"],
		imgLink: "Template 3.png",
		demoLink: "https://abdelkarim-achlaih.github.io/Template-Three/",
		codeLink: "",
		desc: "In this project, I transformed a given PSD design into a fully functional website using HTML, CSS and JavaScript. I meticulously coded and optimized the design to ensure it's responsive and accessible, providing a seamless user experience across various devices and browsers.",
		types: ["templates"],
	},
];
export let techs = {
	HTML: "fa-brands fa-html5",
	CSS: "fa-brands fa-css3-alt",
	JavaScript: "fa-brands fa-square-js",
	Bootstrap: "fa-brands fa-bootstrap",
	Sass: "fa-brands fa-sass",
	WordPress: "fa-brands fa-wordpress",
	PHP: "fa-brands fa-php",
	MySQL: "fa-solid fa-database",
};
